name: BioContainers
description: An open-source and community-driven framework for software standardization
url: http://biocontainers.pro
markdown: kramdown
#pygments: false
#highlighter: pygments
timezone: UTC
encoding: utf-8
exclude: [vendor]
baseurl: /
series:
    "101":
      desc: "Basics"
      sort: 1
    "developer-manual":
      desc: "Developer tutorial"
      sort: 2
    "faqs":
      desc: "BioContainers FAQS"
      sort: 3
    "containers-examples":
      desc: "Containers Examples"
      sort: 4
