name: BioContainers
description: An open-source and community-driven framework for software standardization
url: http://biocontainers.pro
markdown: kramdown
#pygments: false
#highlighter: pygments
timezone: UTC
encoding: utf-8
exclude: [vendor]
baseurl: /
series:
    "101":
      desc: "Basics"
      sort: 1
    "beginner":
      desc: "Beginner tutorial"
      sort: 2
    "user-manual":
      desc: "User tutorial"
      sort: 3
    "developer-manual":
      desc: "Developer tutorial"
      sort: 4
    "snipspector_adv":
      desc: "Advanced Tutorial"
      sort: 5
